// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OgrenciBilgiSistemi.Data;

#nullable disable

namespace OgrenciBilgiSistemi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251123124038_ziyaretciler1")]
    partial class ziyaretciler1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.BirimModel", b =>
                {
                    b.Property<int>("BirimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BirimId"));

                    b.Property<string>("BirimAd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("BirimDurum")
                        .HasColumnType("bit");

                    b.Property<bool>("BirimSinifMi")
                        .HasColumnType("bit");

                    b.HasKey("BirimId");

                    b.ToTable("Birimler");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.CihazModel", b =>
                {
                    b.Property<int>("CihazId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CihazId"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("CihazAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CihazKodu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("DonanimTipi")
                        .HasColumnType("tinyint");

                    b.Property<string>("IpAdresi")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<short>("IstasyonTipi")
                        .HasColumnType("smallint");

                    b.Property<int?>("PortNo")
                        .HasColumnType("int");

                    b.HasKey("CihazId");

                    b.HasIndex("CihazAdi")
                        .IsUnique();

                    b.HasIndex("CihazKodu")
                        .IsUnique();

                    b.HasIndex("IstasyonTipi");

                    b.ToTable("Cihazlar");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.KitapDetayModel", b =>
                {
                    b.Property<int>("KitapDetayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KitapDetayId"));

                    b.Property<DateTime>("KitapAlTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("KitapDurum")
                        .HasColumnType("int");

                    b.Property<int>("KitapId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("KitapVerTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.HasKey("KitapDetayId");

                    b.HasIndex("KitapId");

                    b.HasIndex("OgrenciId");

                    b.ToTable("KitapDetaylar");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.KitapModel", b =>
                {
                    b.Property<int>("KitapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KitapId"));

                    b.Property<string>("KitapAd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("KitapDurum")
                        .HasColumnType("bit");

                    b.Property<string>("KitapGorsel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KitapGun")
                        .HasColumnType("int");

                    b.Property<string>("KitapTurAd")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("KitapId");

                    b.ToTable("Kitaplar");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.KullaniciMenuModel", b =>
                {
                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("MenuOgeId")
                        .HasColumnType("int");

                    b.HasKey("KullaniciId", "MenuOgeId");

                    b.HasIndex("MenuOgeId");

                    b.ToTable("KullaniciMenuOgeler");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.KullaniciModel", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciId"));

                    b.Property<bool>("AdminMi")
                        .HasColumnType("bit");

                    b.Property<bool>("BeniHatirla")
                        .HasColumnType("bit");

                    b.Property<int?>("BirimId")
                        .HasColumnType("int");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("KullaniciDurum")
                        .HasColumnType("bit");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KullaniciId");

                    b.HasIndex("BirimId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.MenuOgeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AnaMenuId")
                        .HasColumnType("int");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Controller")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GerekliRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sirala")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnaMenuId", "Sirala");

                    b.ToTable("MenuOgeler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "Index",
                            Baslik = "Ana Sayfa",
                            Controller = "Home",
                            Sirala = 1
                        },
                        new
                        {
                            Id = 2,
                            Baslik = "Personeller",
                            Sirala = 2
                        },
                        new
                        {
                            Id = 3,
                            Action = "Index",
                            AnaMenuId = 2,
                            Baslik = "Birim Listesi",
                            Controller = "Birimler",
                            Sirala = 1
                        },
                        new
                        {
                            Id = 4,
                            Action = "Index",
                            AnaMenuId = 2,
                            Baslik = "Personel Listesi",
                            Controller = "Personeller",
                            Sirala = 2
                        },
                        new
                        {
                            Id = 5,
                            Baslik = "Öğrenciler",
                            Sirala = 3
                        },
                        new
                        {
                            Id = 6,
                            Action = "Index",
                            AnaMenuId = 5,
                            Baslik = "Öğrenci İşlemleri",
                            Controller = "Ogrenciler",
                            Sirala = 1
                        },
                        new
                        {
                            Id = 7,
                            Action = "Index",
                            AnaMenuId = 5,
                            Baslik = "Aidat İşlemleri",
                            Controller = "OgrenciAidat",
                            Sirala = 2
                        },
                        new
                        {
                            Id = 8,
                            Action = "Index",
                            AnaMenuId = 5,
                            Baslik = "Yemekhane İşlemleri",
                            Controller = "OgrenciYemekhane",
                            Sirala = 3
                        },
                        new
                        {
                            Id = 9,
                            Baslik = "Ziyaretçiler",
                            Sirala = 8
                        },
                        new
                        {
                            Id = 10,
                            Action = "Index",
                            AnaMenuId = 9,
                            Baslik = "Ziyaretçi İşlemleri",
                            Controller = "Ziyaretci",
                            Sirala = 1
                        },
                        new
                        {
                            Id = 11,
                            Baslik = "Kullanıcılar",
                            Sirala = 4
                        },
                        new
                        {
                            Id = 12,
                            Action = "Index",
                            AnaMenuId = 11,
                            Baslik = "Kullanıcı Listesi",
                            Controller = "Kullanicilar",
                            Sirala = 1
                        },
                        new
                        {
                            Id = 13,
                            Baslik = "Kitaplar",
                            Sirala = 5
                        },
                        new
                        {
                            Id = 14,
                            Action = "Index",
                            AnaMenuId = 13,
                            Baslik = "Kitap Listesi",
                            Controller = "Kitaplar",
                            Sirala = 1
                        },
                        new
                        {
                            Id = 15,
                            Action = "Index",
                            AnaMenuId = 13,
                            Baslik = "Kitap Hareketleri",
                            Controller = "KitapDetaylar",
                            Sirala = 2
                        },
                        new
                        {
                            Id = 16,
                            Baslik = "Cihazlar",
                            Sirala = 6
                        },
                        new
                        {
                            Id = 17,
                            Action = "Index",
                            AnaMenuId = 16,
                            Baslik = "Cihaz Listesi",
                            Controller = "Cihazlar",
                            Sirala = 1
                        },
                        new
                        {
                            Id = 18,
                            Baslik = "Raporlar",
                            Sirala = 7
                        },
                        new
                        {
                            Id = 19,
                            Action = "Detay",
                            AnaMenuId = 18,
                            Baslik = "Öğrenci Giriş Çıkış Raporları",
                            Controller = "OgrenciGirisCikis",
                            Sirala = 1
                        },
                        new
                        {
                            Id = 20,
                            Action = "OgrenciVeliRapor",
                            AnaMenuId = 18,
                            Baslik = "Öğrenci Veli Raporu",
                            Controller = "Ogrenciler",
                            Sirala = 2
                        },
                        new
                        {
                            Id = 21,
                            Action = "AidatRapor",
                            AnaMenuId = 18,
                            Baslik = "Öğrenci Aidat Raporu",
                            Controller = "OgrenciAidat",
                            Sirala = 3
                        },
                        new
                        {
                            Id = 22,
                            Action = "YemekRapor",
                            AnaMenuId = 18,
                            Baslik = "Öğrenci Yemek Raporu",
                            Controller = "OgrenciYemekhane",
                            Sirala = 4
                        },
                        new
                        {
                            Id = 23,
                            Baslik = "KartOku",
                            Sirala = 8
                        },
                        new
                        {
                            Id = 24,
                            Action = "Index",
                            AnaMenuId = 23,
                            Baslik = "Kart Okuma Ekranı",
                            Controller = "KartOku",
                            Sirala = 1
                        });
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.OgrenciAidatModel", b =>
                {
                    b.Property<int>("OgrenciAidatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciAidatId"));

                    b.Property<int>("BaslangicYil")
                        .HasColumnType("int");

                    b.Property<decimal>("Borc")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Muaf")
                        .HasColumnType("bit");

                    b.Property<decimal>("Odenen")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SonOdemeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("OgrenciAidatId");

                    b.HasIndex("OgrenciId", "BaslangicYil")
                        .IsUnique();

                    b.ToTable("OgrenciAidatlar", t =>
                        {
                            t.HasCheckConstraint("CK_Aidat_BaslangicYil", "[BaslangicYil] BETWEEN 2000 AND 2100");

                            t.HasCheckConstraint("CK_Aidat_Pozitif", "[Borc] >= 0 AND [Odenen] >= 0");
                        });
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.OgrenciAidatOdemeModel", b =>
                {
                    b.Property<int>("OgrenciAidatOdemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciAidatOdemeId"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OdemeTipi")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OgrenciAidatId")
                        .HasColumnType("int");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OgrenciAidatOdemeId");

                    b.HasIndex("OgrenciAidatId", "OdemeTarihi");

                    b.ToTable("OgrenciAidatOdemeler", t =>
                        {
                            t.HasCheckConstraint("CK_AidatOdeme_Tutar_NonNegative", "[Tutar] >= 0");
                        });
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.OgrenciAidatTarifeModel", b =>
                {
                    b.Property<int>("OgrenciAidatTarifeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciAidatTarifeId"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("BaslangicYil")
                        .HasColumnType("int");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OgrenciAidatTarifeId");

                    b.HasIndex("BaslangicYil")
                        .IsUnique();

                    b.ToTable("OgrenciAidatTarifeler", t =>
                        {
                            t.HasCheckConstraint("CK_Tarife_BaslangicYil", "[BaslangicYil] BETWEEN 2000 AND 2100");

                            t.HasCheckConstraint("CK_Tarife_Tutar", "[Tutar] >= 0");
                        });
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.OgrenciDetayModel", b =>
                {
                    b.Property<int>("OgrenciDetayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciDetayId"));

                    b.Property<int?>("CihazId")
                        .HasColumnType("int");

                    b.Property<short>("IstasyonTipi")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("OgrenciCTarih")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OgrenciGTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("OgrenciGecisTipi")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<string>("OgrenciResimYolu")
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("OgrenciSmsGonderildi")
                        .HasColumnType("bit");

                    b.HasKey("OgrenciDetayId");

                    b.HasIndex("CihazId");

                    b.HasIndex("OgrenciCTarih");

                    b.HasIndex("OgrenciGTarih");

                    b.HasIndex("OgrenciId", "IstasyonTipi");

                    b.ToTable("OgrenciDetaylar");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.OgrenciModel", b =>
                {
                    b.Property<int>("OgrenciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciId"));

                    b.Property<int?>("BirimId")
                        .HasColumnType("int");

                    b.Property<string>("OgrenciAdSoyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OgrenciCikisDurumu")
                        .HasColumnType("int");

                    b.Property<bool>("OgrenciDurum")
                        .HasColumnType("bit");

                    b.Property<string>("OgrenciGorsel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OgrenciKartNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("OgrenciNo")
                        .HasColumnType("int");

                    b.Property<int?>("OgrenciVeliId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonelId")
                        .HasColumnType("int");

                    b.HasKey("OgrenciId");

                    b.HasIndex("BirimId");

                    b.HasIndex("OgrenciVeliId");

                    b.HasIndex("PersonelId");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.OgrenciVeliModel", b =>
                {
                    b.Property<int>("OgrenciVeliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciVeliId"));

                    b.Property<string>("VeliAdSoyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VeliAdres")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("VeliDurum")
                        .HasColumnType("bit");

                    b.Property<string>("VeliEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VeliIsYeri")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VeliMeslek")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VeliTelefon")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("VeliYakinlik")
                        .HasColumnType("int");

                    b.HasKey("OgrenciVeliId");

                    b.ToTable("OgrenciVeliler");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.OgrenciYemekModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int>("Ay")
                        .HasColumnType("int");

                    b.Property<string>("Not")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<int>("Yil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OgrenciId", "Yil", "Ay")
                        .IsUnique();

                    b.ToTable("OgrenciYemekler");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.OgrenciYemekOdemeModel", b =>
                {
                    b.Property<int>("OgrenciYemekOdemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciYemekOdemeId"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Ay")
                        .HasColumnType("int");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Yil")
                        .HasColumnType("int");

                    b.HasKey("OgrenciYemekOdemeId");

                    b.HasIndex("OgrenciId", "Yil", "Ay");

                    b.ToTable("OgrenciYemekOdemeler");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.OgrenciYemekTarifeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("AylikTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<int>("Yil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OgrenciId", "Yil")
                        .IsUnique();

                    b.ToTable("OgrenciYemekTarifeler");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.PersonelDetayModel", b =>
                {
                    b.Property<int>("PersonelDetayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonelDetayId"));

                    b.Property<int?>("CihazId")
                        .HasColumnType("int");

                    b.Property<short>("IstasyonTipi")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("PersonelCTarih")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PersonelGTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("PersonelGecisTipi")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<string>("PersonelResimYolu")
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("PersonelSmsGonderildi")
                        .HasColumnType("bit");

                    b.HasKey("PersonelDetayId");

                    b.HasIndex("CihazId");

                    b.HasIndex("PersonelId");

                    b.ToTable("PersonelDetaylar");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.PersonelModel", b =>
                {
                    b.Property<int>("PersonelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonelId"));

                    b.Property<int?>("BirimId")
                        .HasColumnType("int");

                    b.Property<string>("PersonelAdSoyad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("PersonelDurum")
                        .HasColumnType("bit");

                    b.Property<string>("PersonelEmail")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PersonelGorselPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonelKartNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PersonelTelefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("PersonelTipi")
                        .HasColumnType("tinyint");

                    b.HasKey("PersonelId");

                    b.HasIndex("BirimId");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.ZiyaretciModel", b =>
                {
                    b.Property<int>("ZiyaretciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZiyaretciId"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Adres")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int?>("CihazId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CikisZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GirisZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("KartNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("KartVerildiMi")
                        .HasColumnType("bit");

                    b.Property<string>("Not")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("PersonelId")
                        .HasColumnType("int");

                    b.Property<string>("TcKimlikNo")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ZiyaretSebebi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ZiyaretciId");

                    b.HasIndex("PersonelId");

                    b.ToTable("Ziyaretciler");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.KitapDetayModel", b =>
                {
                    b.HasOne("OgrenciBilgiSistemi.Models.KitapModel", "Kitap")
                        .WithMany()
                        .HasForeignKey("KitapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OgrenciBilgiSistemi.Models.OgrenciModel", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kitap");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.KullaniciMenuModel", b =>
                {
                    b.HasOne("OgrenciBilgiSistemi.Models.KullaniciModel", "Kullanici")
                        .WithMany("KullaniciMenuler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OgrenciBilgiSistemi.Models.MenuOgeModel", "MenuOge")
                        .WithMany("KullaniciMenuler")
                        .HasForeignKey("MenuOgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("MenuOge");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.KullaniciModel", b =>
                {
                    b.HasOne("OgrenciBilgiSistemi.Models.BirimModel", "Birim")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("BirimId");

                    b.Navigation("Birim");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.MenuOgeModel", b =>
                {
                    b.HasOne("OgrenciBilgiSistemi.Models.MenuOgeModel", "AnaMenu")
                        .WithMany("AltMenuler")
                        .HasForeignKey("AnaMenuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AnaMenu");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.OgrenciAidatModel", b =>
                {
                    b.HasOne("OgrenciBilgiSistemi.Models.OgrenciModel", "Ogrenci")
                        .WithMany("OgrenciAidatlar")
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.OgrenciAidatOdemeModel", b =>
                {
                    b.HasOne("OgrenciBilgiSistemi.Models.OgrenciAidatModel", "OgrenciAidat")
                        .WithMany("Odemeler")
                        .HasForeignKey("OgrenciAidatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OgrenciAidat");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.OgrenciDetayModel", b =>
                {
                    b.HasOne("OgrenciBilgiSistemi.Models.CihazModel", "Cihaz")
                        .WithMany()
                        .HasForeignKey("CihazId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OgrenciBilgiSistemi.Models.OgrenciModel", "Ogrenci")
                        .WithMany("OgrenciDetaylar")
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cihaz");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.OgrenciModel", b =>
                {
                    b.HasOne("OgrenciBilgiSistemi.Models.BirimModel", "Birim")
                        .WithMany("Ogrenciler")
                        .HasForeignKey("BirimId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OgrenciBilgiSistemi.Models.OgrenciVeliModel", "OgrenciVeli")
                        .WithMany("Ogrenciler")
                        .HasForeignKey("OgrenciVeliId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OgrenciBilgiSistemi.Models.PersonelModel", "Personel")
                        .WithMany("Ogrenciler")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Birim");

                    b.Navigation("OgrenciVeli");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.OgrenciYemekModel", b =>
                {
                    b.HasOne("OgrenciBilgiSistemi.Models.OgrenciModel", "Ogrenci")
                        .WithMany("OgrenciYemekler")
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.OgrenciYemekOdemeModel", b =>
                {
                    b.HasOne("OgrenciBilgiSistemi.Models.OgrenciModel", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.OgrenciYemekTarifeModel", b =>
                {
                    b.HasOne("OgrenciBilgiSistemi.Models.OgrenciModel", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.PersonelDetayModel", b =>
                {
                    b.HasOne("OgrenciBilgiSistemi.Models.CihazModel", "Cihaz")
                        .WithMany()
                        .HasForeignKey("CihazId");

                    b.HasOne("OgrenciBilgiSistemi.Models.PersonelModel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cihaz");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.PersonelModel", b =>
                {
                    b.HasOne("OgrenciBilgiSistemi.Models.BirimModel", "Birim")
                        .WithMany("Personeller")
                        .HasForeignKey("BirimId");

                    b.Navigation("Birim");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.ZiyaretciModel", b =>
                {
                    b.HasOne("OgrenciBilgiSistemi.Models.PersonelModel", "Personel")
                        .WithMany("Ziyaretciler")
                        .HasForeignKey("PersonelId");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.BirimModel", b =>
                {
                    b.Navigation("Kullanicilar");

                    b.Navigation("Ogrenciler");

                    b.Navigation("Personeller");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.KullaniciModel", b =>
                {
                    b.Navigation("KullaniciMenuler");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.MenuOgeModel", b =>
                {
                    b.Navigation("AltMenuler");

                    b.Navigation("KullaniciMenuler");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.OgrenciAidatModel", b =>
                {
                    b.Navigation("Odemeler");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.OgrenciModel", b =>
                {
                    b.Navigation("OgrenciAidatlar");

                    b.Navigation("OgrenciDetaylar");

                    b.Navigation("OgrenciYemekler");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.OgrenciVeliModel", b =>
                {
                    b.Navigation("Ogrenciler");
                });

            modelBuilder.Entity("OgrenciBilgiSistemi.Models.PersonelModel", b =>
                {
                    b.Navigation("Ogrenciler");

                    b.Navigation("Ziyaretciler");
                });
#pragma warning restore 612, 618
        }
    }
}
